(ns soda-ash.core
  (:require
   [soda-ash.helpers :as h]
   [soda-ash.elements.button :as button]
   [soda-ash.elements.container :as container]
   [soda-ash.elements.divider :as divider]
   [soda-ash.elements.flag :as flag]
   [soda-ash.elements.header :as header]
   [soda-ash.elements.icon :as icon]
   ))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ELEMENTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; button

(def button' button/class)
(def button button/component)

(def button-primary' button/class-primary)
(def button-primary button/component-primary)

(def button-secondary' button/class-secondary)
(def button-secondary button/component-secondary)

(def button-animated' button/class-animated)
(def button-animated button/component-animated)

(def button-vertical-animated' button/class-vertical-animated)
(def button-vertical-animated button/component-vertical-animated)

(def button-animated-fade' button/class-animated-fade)
(def button-animated-fade button/component-animated-fade)

(def button-labeled' button/class-labeled)
(def button-labeled button/component-labeled)

(def button-left-labeled' button/class-left-labeled)
(def button-left-labeled button/component-left-labeled)

(def button-icon' button/class-icon)
(def button-icon button/component-icon)

(def button-labeled-icon' button/class-labeled-icon)
(def button-labeled-icon button/component-labeled-icon)

(def button-right-labeled-icon' button/class-right-labeled-icon)
(def button-right-labeled-icon button/component-right-labeled-icon)

(def button-basic' button/class-basic)
(def button-basic button/component-basic)

(def button-inverted' button/class-inverted)
(def button-inverted button/component-inverted)

(def button-inverted-basic' button/class-inverted-basic)
(def button-inverted-basic button/component-inverted-basic)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; container

(def container' container/class)
(def container container/component)

(def container-text' container/class-text)
(def container-text container/component-text)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; divider

(def divider' divider/class)
(def divider divider/component)

(def divider-vertical' divider/class-vertical)
(def divider-vertical divider/component-vertical)

(def divider-horizontal' divider/class-horizontal)
(def divider-horizontal divider/component-horizontal)

(def divider-horizontal-header' divider/class-horizontal-header)
(def divider-horizontal-header divider/component-horizontal-header)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; flag

(def flag-ae' flag/class-ae)
(def flag-ae flag/component-ae)

(def flag-af' flag/class-af)
(def flag-af flag/component-af)

(def flag-ag' flag/class-ag)
(def flag-ag flag/component-ag)

(def flag-ai' flag/class-ai)
(def flag-ai flag/component-ai)

(def flag-al' flag/class-al)
(def flag-al flag/component-al)

(def flag-am' flag/class-am)
(def flag-am flag/component-am)

(def flag-an' flag/class-an)
(def flag-an flag/component-an)

(def flag-ao' flag/class-ao)
(def flag-ao flag/component-ao)

(def flag-ar' flag/class-ar)
(def flag-ar flag/component-ar)

(def flag-as' flag/class-as)
(def flag-as flag/component-as)

(def flag-at' flag/class-at)
(def flag-at flag/component-at)

(def flag-au' flag/class-au)
(def flag-au flag/component-au)

(def flag-aw' flag/class-aw)
(def flag-aw flag/component-aw)

(def flag-ax' flag/class-ax)
(def flag-ax flag/component-ax)

(def flag-az' flag/class-az)
(def flag-az flag/component-az)

(def flag-ba' flag/class-ba)
(def flag-ba flag/component-ba)

(def flag-bb' flag/class-bb)
(def flag-bb flag/component-bb)

(def flag-bd' flag/class-bd)
(def flag-bd flag/component-bd)

(def flag-be' flag/class-be)
(def flag-be flag/component-be)

(def flag-bf' flag/class-bf)
(def flag-bf flag/component-bf)

(def flag-bg' flag/class-bg)
(def flag-bg flag/component-bg)

(def flag-bh' flag/class-bh)
(def flag-bh flag/component-bh)

(def flag-bi' flag/class-bi)
(def flag-bi flag/component-bi)

(def flag-bj' flag/class-bj)
(def flag-bj flag/component-bj)

(def flag-bm' flag/class-bm)
(def flag-bm flag/component-bm)

(def flag-bn' flag/class-bn)
(def flag-bn flag/component-bn)

(def flag-bo' flag/class-bo)
(def flag-bo flag/component-bo)

(def flag-br' flag/class-br)
(def flag-br flag/component-br)

(def flag-bs' flag/class-bs)
(def flag-bs flag/component-bs)

(def flag-bt' flag/class-bt)
(def flag-bt flag/component-bt)

(def flag-bv' flag/class-bv)
(def flag-bv flag/component-bv)

(def flag-bw' flag/class-bw)
(def flag-bw flag/component-bw)

(def flag-by' flag/class-by)
(def flag-by flag/component-by)

(def flag-bz' flag/class-bz)
(def flag-bz flag/component-bz)

(def flag-ca' flag/class-ca)
(def flag-ca flag/component-ca)

(def flag-cc' flag/class-cc)
(def flag-cc flag/component-cc)

(def flag-cd' flag/class-cd)
(def flag-cd flag/component-cd)

(def flag-cf' flag/class-cf)
(def flag-cf flag/component-cf)

(def flag-cg' flag/class-cg)
(def flag-cg flag/component-cg)

(def flag-ch' flag/class-ch)
(def flag-ch flag/component-ch)

(def flag-ci' flag/class-ci)
(def flag-ci flag/component-ci)

(def flag-ck' flag/class-ck)
(def flag-ck flag/component-ck)

(def flag-cl' flag/class-cl)
(def flag-cl flag/component-cl)

(def flag-cm' flag/class-cm)
(def flag-cm flag/component-cm)

(def flag-cn' flag/class-cn)
(def flag-cn flag/component-cn)

(def flag-co' flag/class-co)
(def flag-co flag/component-co)

(def flag-cr' flag/class-cr)
(def flag-cr flag/component-cr)

(def flag-cs' flag/class-cs)
(def flag-cs flag/component-cs)

(def flag-cu' flag/class-cu)
(def flag-cu flag/component-cu)

(def flag-cv' flag/class-cv)
(def flag-cv flag/component-cv)

(def flag-cx' flag/class-cx)
(def flag-cx flag/component-cx)

(def flag-cy' flag/class-cy)
(def flag-cy flag/component-cy)

(def flag-cz' flag/class-cz)
(def flag-cz flag/component-cz)

(def flag-de' flag/class-de)
(def flag-de flag/component-de)

(def flag-dj' flag/class-dj)
(def flag-dj flag/component-dj)

(def flag-dk' flag/class-dk)
(def flag-dk flag/component-dk)

(def flag-dm' flag/class-dm)
(def flag-dm flag/component-dm)

(def flag-do' flag/class-do)
(def flag-do flag/component-do)

(def flag-dz' flag/class-dz)
(def flag-dz flag/component-dz)

(def flag-ec' flag/class-ec)
(def flag-ec flag/component-ec)

(def flag-ee' flag/class-ee)
(def flag-ee flag/component-ee)

(def flag-eg' flag/class-eg)
(def flag-eg flag/component-eg)

(def flag-eh' flag/class-eh)
(def flag-eh flag/component-eh)

(def flag-er' flag/class-er)
(def flag-er flag/component-er)

(def flag-es' flag/class-es)
(def flag-es flag/component-es)

(def flag-et' flag/class-et)
(def flag-et flag/component-et)

(def flag-eu' flag/class-eu)
(def flag-eu flag/component-eu)

(def flag-fi' flag/class-fi)
(def flag-fi flag/component-fi)

(def flag-fj' flag/class-fj)
(def flag-fj flag/component-fj)

(def flag-fk' flag/class-fk)
(def flag-fk flag/component-fk)

(def flag-fm' flag/class-fm)
(def flag-fm flag/component-fm)

(def flag-fo' flag/class-fo)
(def flag-fo flag/component-fo)

(def flag-fr' flag/class-fr)
(def flag-fr flag/component-fr)

(def flag-ga' flag/class-ga)
(def flag-ga flag/component-ga)

(def flag-gb' flag/class-gb)
(def flag-gb flag/component-gb)

(def flag-gd' flag/class-gd)
(def flag-gd flag/component-gd)

(def flag-ge' flag/class-ge)
(def flag-ge flag/component-ge)

(def flag-gf' flag/class-gf)
(def flag-gf flag/component-gf)

(def flag-gh' flag/class-gh)
(def flag-gh flag/component-gh)

(def flag-gi' flag/class-gi)
(def flag-gi flag/component-gi)

(def flag-gl' flag/class-gl)
(def flag-gl flag/component-gl)

(def flag-gm' flag/class-gm)
(def flag-gm flag/component-gm)

(def flag-gn' flag/class-gn)
(def flag-gn flag/component-gn)

(def flag-gp' flag/class-gp)
(def flag-gp flag/component-gp)

(def flag-gq' flag/class-gq)
(def flag-gq flag/component-gq)

(def flag-gr' flag/class-gr)
(def flag-gr flag/component-gr)

(def flag-gs' flag/class-gs)
(def flag-gs flag/component-gs)

(def flag-gt' flag/class-gt)
(def flag-gt flag/component-gt)

(def flag-gu' flag/class-gu)
(def flag-gu flag/component-gu)

(def flag-gw' flag/class-gw)
(def flag-gw flag/component-gw)

(def flag-gy' flag/class-gy)
(def flag-gy flag/component-gy)

(def flag-hk' flag/class-hk)
(def flag-hk flag/component-hk)

(def flag-hm' flag/class-hm)
(def flag-hm flag/component-hm)

(def flag-hn' flag/class-hn)
(def flag-hn flag/component-hn)

(def flag-hr' flag/class-hr)
(def flag-hr flag/component-hr)

(def flag-ht' flag/class-ht)
(def flag-ht flag/component-ht)

(def flag-hu' flag/class-hu)
(def flag-hu flag/component-hu)

(def flag-id' flag/class-id)
(def flag-id flag/component-id)

(def flag-ie' flag/class-ie)
(def flag-ie flag/component-ie)

(def flag-il' flag/class-il)
(def flag-il flag/component-il)

(def flag-in' flag/class-in)
(def flag-in flag/component-in)

(def flag-io' flag/class-io)
(def flag-io flag/component-io)

(def flag-iq' flag/class-iq)
(def flag-iq flag/component-iq)

(def flag-ir' flag/class-ir)
(def flag-ir flag/component-ir)

(def flag-is' flag/class-is)
(def flag-is flag/component-is)

(def flag-it' flag/class-it)
(def flag-it flag/component-it)

(def flag-jm' flag/class-jm)
(def flag-jm flag/component-jm)

(def flag-jo' flag/class-jo)
(def flag-jo flag/component-jo)

(def flag-jp' flag/class-jp)
(def flag-jp flag/component-jp)

(def flag-ke' flag/class-ke)
(def flag-ke flag/component-ke)

(def flag-kg' flag/class-kg)
(def flag-kg flag/component-kg)

(def flag-kh' flag/class-kh)
(def flag-kh flag/component-kh)

(def flag-ki' flag/class-ki)
(def flag-ki flag/component-ki)

(def flag-km' flag/class-km)
(def flag-km flag/component-km)

(def flag-kn' flag/class-kn)
(def flag-kn flag/component-kn)

(def flag-kp' flag/class-kp)
(def flag-kp flag/component-kp)

(def flag-kr' flag/class-kr)
(def flag-kr flag/component-kr)

(def flag-kw' flag/class-kw)
(def flag-kw flag/component-kw)

(def flag-ky' flag/class-ky)
(def flag-ky flag/component-ky)

(def flag-kz' flag/class-kz)
(def flag-kz flag/component-kz)

(def flag-la' flag/class-la)
(def flag-la flag/component-la)

(def flag-lb' flag/class-lb)
(def flag-lb flag/component-lb)

(def flag-lc' flag/class-lc)
(def flag-lc flag/component-lc)

(def flag-li' flag/class-li)
(def flag-li flag/component-li)

(def flag-lk' flag/class-lk)
(def flag-lk flag/component-lk)

(def flag-lr' flag/class-lr)
(def flag-lr flag/component-lr)

(def flag-ls' flag/class-ls)
(def flag-ls flag/component-ls)

(def flag-lt' flag/class-lt)
(def flag-lt flag/component-lt)

(def flag-lu' flag/class-lu)
(def flag-lu flag/component-lu)

(def flag-lv' flag/class-lv)
(def flag-lv flag/component-lv)

(def flag-ly' flag/class-ly)
(def flag-ly flag/component-ly)

(def flag-ma' flag/class-ma)
(def flag-ma flag/component-ma)

(def flag-mc' flag/class-mc)
(def flag-mc flag/component-mc)

(def flag-md' flag/class-md)
(def flag-md flag/component-md)

(def flag-me' flag/class-me)
(def flag-me flag/component-me)

(def flag-mg' flag/class-mg)
(def flag-mg flag/component-mg)

(def flag-mh' flag/class-mh)
(def flag-mh flag/component-mh)

(def flag-mk' flag/class-mk)
(def flag-mk flag/component-mk)

(def flag-ml' flag/class-ml)
(def flag-ml flag/component-ml)

(def flag-mm' flag/class-mm)
(def flag-mm flag/component-mm)

(def flag-mn' flag/class-mn)
(def flag-mn flag/component-mn)

(def flag-mo' flag/class-mo)
(def flag-mo flag/component-mo)

(def flag-mp' flag/class-mp)
(def flag-mp flag/component-mp)

(def flag-mq' flag/class-mq)
(def flag-mq flag/component-mq)

(def flag-mr' flag/class-mr)
(def flag-mr flag/component-mr)

(def flag-ms' flag/class-ms)
(def flag-ms flag/component-ms)

(def flag-mt' flag/class-mt)
(def flag-mt flag/component-mt)

(def flag-mu' flag/class-mu)
(def flag-mu flag/component-mu)

(def flag-mv' flag/class-mv)
(def flag-mv flag/component-mv)

(def flag-mw' flag/class-mw)
(def flag-mw flag/component-mw)

(def flag-mx' flag/class-mx)
(def flag-mx flag/component-mx)

(def flag-my' flag/class-my)
(def flag-my flag/component-my)

(def flag-mz' flag/class-mz)
(def flag-mz flag/component-mz)

(def flag-na' flag/class-na)
(def flag-na flag/component-na)

(def flag-nc' flag/class-nc)
(def flag-nc flag/component-nc)

(def flag-ne' flag/class-ne)
(def flag-ne flag/component-ne)

(def flag-nf' flag/class-nf)
(def flag-nf flag/component-nf)

(def flag-ng' flag/class-ng)
(def flag-ng flag/component-ng)

(def flag-ni' flag/class-ni)
(def flag-ni flag/component-ni)

(def flag-nl' flag/class-nl)
(def flag-nl flag/component-nl)

(def flag-no' flag/class-no)
(def flag-no flag/component-no)

(def flag-np' flag/class-np)
(def flag-np flag/component-np)

(def flag-nr' flag/class-nr)
(def flag-nr flag/component-nr)

(def flag-nu' flag/class-nu)
(def flag-nu flag/component-nu)

(def flag-nz' flag/class-nz)
(def flag-nz flag/component-nz)

(def flag-om' flag/class-om)
(def flag-om flag/component-om)

(def flag-pa' flag/class-pa)
(def flag-pa flag/component-pa)

(def flag-pe' flag/class-pe)
(def flag-pe flag/component-pe)

(def flag-pf' flag/class-pf)
(def flag-pf flag/component-pf)

(def flag-pg' flag/class-pg)
(def flag-pg flag/component-pg)

(def flag-ph' flag/class-ph)
(def flag-ph flag/component-ph)

(def flag-pk' flag/class-pk)
(def flag-pk flag/component-pk)

(def flag-pl' flag/class-pl)
(def flag-pl flag/component-pl)

(def flag-pm' flag/class-pm)
(def flag-pm flag/component-pm)

(def flag-pn' flag/class-pn)
(def flag-pn flag/component-pn)

(def flag-pr' flag/class-pr)
(def flag-pr flag/component-pr)

(def flag-ps' flag/class-ps)
(def flag-ps flag/component-ps)

(def flag-pt' flag/class-pt)
(def flag-pt flag/component-pt)

(def flag-pw' flag/class-pw)
(def flag-pw flag/component-pw)

(def flag-py' flag/class-py)
(def flag-py flag/component-py)

(def flag-qa' flag/class-qa)
(def flag-qa flag/component-qa)

(def flag-re' flag/class-re)
(def flag-re flag/component-re)

(def flag-ro' flag/class-ro)
(def flag-ro flag/component-ro)

(def flag-rs' flag/class-rs)
(def flag-rs flag/component-rs)

(def flag-ru' flag/class-ru)
(def flag-ru flag/component-ru)

(def flag-rw' flag/class-rw)
(def flag-rw flag/component-rw)

(def flag-sa' flag/class-sa)
(def flag-sa flag/component-sa)

(def flag-sb' flag/class-sb)
(def flag-sb flag/component-sb)

(def flag-sc' flag/class-sc)
(def flag-sc flag/component-sc)

(def flag-sd' flag/class-sd)
(def flag-sd flag/component-sd)

(def flag-se' flag/class-se)
(def flag-se flag/component-se)

(def flag-sg' flag/class-sg)
(def flag-sg flag/component-sg)

(def flag-sh' flag/class-sh)
(def flag-sh flag/component-sh)

(def flag-si' flag/class-si)
(def flag-si flag/component-si)

(def flag-sj' flag/class-sj)
(def flag-sj flag/component-sj)

(def flag-sk' flag/class-sk)
(def flag-sk flag/component-sk)

(def flag-sl' flag/class-sl)
(def flag-sl flag/component-sl)

(def flag-sm' flag/class-sm)
(def flag-sm flag/component-sm)

(def flag-sn' flag/class-sn)
(def flag-sn flag/component-sn)

(def flag-so' flag/class-so)
(def flag-so flag/component-so)

(def flag-sr' flag/class-sr)
(def flag-sr flag/component-sr)

(def flag-st' flag/class-st)
(def flag-st flag/component-st)

(def flag-sv' flag/class-sv)
(def flag-sv flag/component-sv)

(def flag-sy' flag/class-sy)
(def flag-sy flag/component-sy)

(def flag-sz' flag/class-sz)
(def flag-sz flag/component-sz)

(def flag-tc' flag/class-tc)
(def flag-tc flag/component-tc)

(def flag-td' flag/class-td)
(def flag-td flag/component-td)

(def flag-tf' flag/class-tf)
(def flag-tf flag/component-tf)

(def flag-tg' flag/class-tg)
(def flag-tg flag/component-tg)

(def flag-th' flag/class-th)
(def flag-th flag/component-th)

(def flag-tj' flag/class-tj)
(def flag-tj flag/component-tj)

(def flag-tk' flag/class-tk)
(def flag-tk flag/component-tk)

(def flag-tl' flag/class-tl)
(def flag-tl flag/component-tl)

(def flag-tm' flag/class-tm)
(def flag-tm flag/component-tm)

(def flag-tn' flag/class-tn)
(def flag-tn flag/component-tn)

(def flag-to' flag/class-to)
(def flag-to flag/component-to)

(def flag-tr' flag/class-tr)
(def flag-tr flag/component-tr)

(def flag-tt' flag/class-tt)
(def flag-tt flag/component-tt)

(def flag-tv' flag/class-tv)
(def flag-tv flag/component-tv)

(def flag-tw' flag/class-tw)
(def flag-tw flag/component-tw)

(def flag-tz' flag/class-tz)
(def flag-tz flag/component-tz)

(def flag-ua' flag/class-ua)
(def flag-ua flag/component-ua)

(def flag-ug' flag/class-ug)
(def flag-ug flag/component-ug)

(def flag-um' flag/class-um)
(def flag-um flag/component-um)

(def flag-us' flag/class-us)
(def flag-us flag/component-us)

(def flag-uy' flag/class-uy)
(def flag-uy flag/component-uy)

(def flag-uz' flag/class-uz)
(def flag-uz flag/component-uz)

(def flag-va' flag/class-va)
(def flag-va flag/component-va)

(def flag-vc' flag/class-vc)
(def flag-vc flag/component-vc)

(def flag-ve' flag/class-ve)
(def flag-ve flag/component-ve)

(def flag-vg' flag/class-vg)
(def flag-vg flag/component-vg)

(def flag-vi' flag/class-vi)
(def flag-vi flag/component-vi)

(def flag-vn' flag/class-vn)
(def flag-vn flag/component-vn)

(def flag-vu' flag/class-vu)
(def flag-vu flag/component-vu)

(def flag-wf' flag/class-wf)
(def flag-wf flag/component-wf)

(def flag-ws' flag/class-ws)
(def flag-ws flag/component-ws)

(def flag-ye' flag/class-ye)
(def flag-ye flag/component-ye)

(def flag-yt' flag/class-yt)
(def flag-yt flag/component-yt)

(def flag-za' flag/class-za)
(def flag-za flag/component-za)

(def flag-zm' flag/class-zm)
(def flag-zm flag/component-zm)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; header

(def header-h1' header/class-h1)
(def header-h1 header/component-h1)

(def header-h2' header/class-h2)
(def header-h2 header/component-h2)

(def header-h3' header/class-h3)
(def header-h3 header/component-h3)

(def header-h4' header/class-h4)
(def header-h4 header/component-h4)

(def header-h5' header/class-h5)
(def header-h5 header/component-h5)

(def header-huge' header/class-huge)
(def header-huge header/component-huge)

(def header-large' header/class-large)
(def header-large header/component-large)

(def header-medium' header/class-medium)
(def header-medium header/component-medium)

(def header-small' header/class-small)
(def header-small header/component-small)

(def header-tiny' header/class-tiny)
(def header-tiny header/component-tiny)

(def header-icon' header/class-icon)
(def header-icon header/component-icon)

(def header-sub' header/class-sub)
(def header-sub header/component-sub)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; icon

(def icon-alarm' icon/class-alarm)
(def icon-alarm icon/component-alarm)
(def icon-alarm-slash' icon/class-alarm-slash)
(def icon-alarm-slash icon/component-alarm-slash)
(def icon-alarm-outline' icon/class-alarm-outline)
(def icon-alarm-outline icon/component-alarm-outline)
(def icon-alarm-slash-outline' icon/class-alarm-slash-outline)
(def icon-alarm-slash-outline icon/component-alarm-slash-outline)
(def icon-at' icon/class-at)
(def icon-at icon/component-at)
(def icon-browser' icon/class-browser)
(def icon-browser icon/component-browser)
(def icon-bug' icon/class-bug)
(def icon-bug icon/component-bug)
(def icon-calendar-outline' icon/class-calendar-outline)
(def icon-calendar-outline icon/component-calendar-outline)
(def icon-calendar' icon/class-calendar)
(def icon-calendar icon/component-calendar)
(def icon-cloud' icon/class-cloud)
(def icon-cloud icon/component-cloud)
(def icon-comment' icon/class-comment)
(def icon-comment icon/component-comment)
(def icon-comments' icon/class-comments)
(def icon-comments icon/component-comments)
(def icon-comment-outline' icon/class-comment-outline)
(def icon-comment-outline icon/component-comment-outline)
(def icon-comments-outline' icon/class-comments-outline)
(def icon-comments-outline icon/component-comments-outline)
(def icon-copyright' icon/class-copyright)
(def icon-copyright icon/component-copyright)
(def icon-dashboard' icon/class-dashboard)
(def icon-dashboard icon/component-dashboard)
(def icon-dropdown' icon/class-dropdown)
(def icon-dropdown icon/component-dropdown)
(def icon-external-square' icon/class-external-square)
(def icon-external-square icon/component-external-square)
(def icon-external' icon/class-external)
(def icon-external icon/component-external)
(def icon-eyedropper' icon/class-eyedropper)
(def icon-eyedropper icon/component-eyedropper)
(def icon-feed' icon/class-feed)
(def icon-feed icon/component-feed)
(def icon-find' icon/class-find)
(def icon-find icon/component-find)
(def icon-heartbeat' icon/class-heartbeat)
(def icon-heartbeat icon/component-heartbeat)
(def icon-history' icon/class-history)
(def icon-history icon/component-history)
(def icon-home' icon/class-home)
(def icon-home icon/component-home)
(def icon-idea' icon/class-idea)
(def icon-idea icon/component-idea)
(def icon-inbox' icon/class-inbox)
(def icon-inbox icon/component-inbox)
(def icon-lab' icon/class-lab)
(def icon-lab icon/component-lab)
(def icon-mail' icon/class-mail)
(def icon-mail icon/component-mail)
(def icon-mail-outline' icon/class-mail-outline)
(def icon-mail-outline icon/component-mail-outline)
(def icon-mail-square' icon/class-mail-square)
(def icon-mail-square icon/component-mail-square)
(def icon-map' icon/class-map)
(def icon-map icon/component-map)
(def icon-options' icon/class-options)
(def icon-options icon/component-options)
(def icon-paint-brush' icon/class-paint-brush)
(def icon-paint-brush icon/component-paint-brush)
(def icon-payment' icon/class-payment)
(def icon-payment icon/component-payment)
(def icon-phone' icon/class-phone)
(def icon-phone icon/component-phone)
(def icon-phone-square' icon/class-phone-square)
(def icon-phone-square icon/component-phone-square)
(def icon-privacy' icon/class-privacy)
(def icon-privacy icon/component-privacy)
(def icon-protect' icon/class-protect)
(def icon-protect icon/component-protect)
(def icon-search' icon/class-search)
(def icon-search icon/component-search)
(def icon-setting' icon/class-setting)
(def icon-setting icon/component-setting)
(def icon-settings' icon/class-settings)
(def icon-settings icon/component-settings)
(def icon-shop' icon/class-shop)
(def icon-shop icon/component-shop)
(def icon-sidebar' icon/class-sidebar)
(def icon-sidebar icon/component-sidebar)
(def icon-signal' icon/class-signal)
(def icon-signal icon/component-signal)
(def icon-sitemap' icon/class-sitemap)
(def icon-sitemap icon/component-sitemap)
(def icon-tag' icon/class-tag)
(def icon-tag icon/component-tag)
(def icon-tags' icon/class-tags)
(def icon-tags icon/component-tags)
(def icon-tasks' icon/class-tasks)
(def icon-tasks icon/component-tasks)
(def icon-terminal' icon/class-terminal)
(def icon-terminal icon/component-terminal)
(def icon-text-telephone' icon/class-text-telephone)
(def icon-text-telephone icon/component-text-telephone)
(def icon-ticket' icon/class-ticket)
(def icon-ticket icon/component-ticket)
(def icon-trophy' icon/class-trophy)
(def icon-trophy icon/component-trophy)
(def icon-wifi' icon/class-wifi)
(def icon-wifi icon/component-wifi)

(def icon-adjust' icon/class-adjust)
(def icon-adjust icon/component-adjust)
(def icon-add-user' icon/class-add-user)
(def icon-add-user icon/component-add-user)
(def icon-add-to-cart' icon/class-add-to-cart)
(def icon-add-to-cart icon/component-add-to-cart)
(def icon-archive' icon/class-archive)
(def icon-archive icon/component-archive)
(def icon-ban' icon/class-ban)
(def icon-ban icon/component-ban)
(def icon-bookmark' icon/class-bookmark)
(def icon-bookmark icon/component-bookmark)
(def icon-call' icon/class-call)
(def icon-call icon/component-call)
(def icon-call-square' icon/class-call-square)
(def icon-call-square icon/component-call-square)
(def icon-cloud-download' icon/class-cloud-download)
(def icon-cloud-download icon/component-cloud-download)
(def icon-cloud-upload' icon/class-cloud-upload)
(def icon-cloud-upload icon/component-cloud-upload)
(def icon-compress' icon/class-compress)
(def icon-compress icon/component-compress)
(def icon-configure' icon/class-configure)
(def icon-configure icon/component-configure)
(def icon-download' icon/class-download)
(def icon-download icon/component-download)
(def icon-edit' icon/class-edit)
(def icon-edit icon/component-edit)
(def icon-erase' icon/class-erase)
(def icon-erase icon/component-erase)
(def icon-exchange' icon/class-exchange)
(def icon-exchange icon/component-exchange)
(def icon-external-share' icon/class-external-share)
(def icon-external-share icon/component-external-share)
(def icon-expand' icon/class-expand)
(def icon-expand icon/component-expand)
(def icon-filter' icon/class-filter)
(def icon-filter icon/component-filter)
(def icon-flag' icon/class-flag)
(def icon-flag icon/component-flag)
(def icon-flag-outline' icon/class-flag-outline)
(def icon-flag-outline icon/component-flag-outline)
(def icon-forward-mail' icon/class-forward-mail)
(def icon-forward-mail icon/component-forward-mail)
(def icon-hide' icon/class-hide)
(def icon-hide icon/component-hide)
(def icon-in-cart' icon/class-in-cart)
(def icon-in-cart icon/component-in-cart)
(def icon-lock' icon/class-lock)
(def icon-lock icon/component-lock)
(def icon-pin' icon/class-pin)
(def icon-pin icon/component-pin)
(def icon-print' icon/class-print)
(def icon-print icon/component-print)
(def icon-random' icon/class-random)
(def icon-random icon/component-random)
(def icon-recycle' icon/class-recycle)
(def icon-recycle icon/component-recycle)
(def icon-refresh' icon/class-refresh)
(def icon-refresh icon/component-refresh)
(def icon-remove-bookmark' icon/class-remove-bookmark)
(def icon-remove-bookmark icon/component-remove-bookmark)
(def icon-remove-user' icon/class-remove-user)
(def icon-remove-user icon/component-remove-user)
(def icon-repeat' icon/class-repeat)
(def icon-repeat icon/component-repeat)
(def icon-reply-all' icon/class-reply-all)
(def icon-reply-all icon/component-reply-all)
(def icon-reply' icon/class-reply)
(def icon-reply icon/component-reply)
(def icon-retweet' icon/class-retweet)
(def icon-retweet icon/component-retweet)
(def icon-send' icon/class-send)
(def icon-send icon/component-send)
(def icon-send-outline' icon/class-send-outline)
(def icon-send-outline icon/component-send-outline)
(def icon-share-alternate' icon/class-share-alternate)
(def icon-share-alternate icon/component-share-alternate)
(def icon-share-alternate-square' icon/class-share-alternate-square)
(def icon-share-alternate-square icon/component-share-alternate-square)
(def icon-share' icon/class-share)
(def icon-share icon/component-share)
(def icon-share-square' icon/class-share-square)
(def icon-share-square icon/component-share-square)
(def icon-sign-in' icon/class-sign-in)
(def icon-sign-in icon/component-sign-in)
(def icon-sign-out' icon/class-sign-out)
(def icon-sign-out icon/component-sign-out)
(def icon-theme' icon/class-theme)
(def icon-theme icon/component-theme)
(def icon-translate' icon/class-translate)
(def icon-translate icon/component-translate)
(def icon-undo' icon/class-undo)
(def icon-undo icon/component-undo)
(def icon-unhide' icon/class-unhide)
(def icon-unhide icon/component-unhide)
(def icon-unlock-alternate' icon/class-unlock-alternate)
(def icon-unlock-alternate icon/component-unlock-alternate)
(def icon-unlock' icon/class-unlock)
(def icon-unlock icon/component-unlock)
(def icon-upload' icon/class-upload)
(def icon-upload icon/component-upload)
(def icon-wait' icon/class-wait)
(def icon-wait icon/component-wait)
(def icon-wizard' icon/class-wizard)
(def icon-wizard icon/component-wizard)
(def icon-write' icon/class-write)
(def icon-write icon/component-write)
(def icon-write-square' icon/class-write-square)
(def icon-write-square icon/component-write-square)

(def icon-announcement' icon/class-announcement)
(def icon-announcement icon/component-announcement)
(def icon-birthday' icon/class-birthday)
(def icon-birthday icon/component-birthday)
(def icon-help' icon/class-help)
(def icon-help icon/component-help)
(def icon-help-circle' icon/class-help-circle)
(def icon-help-circle icon/component-help-circle)
(def icon-info' icon/class-info)
(def icon-info icon/component-info)
(def icon-info-circle' icon/class-info-circle)
(def icon-info-circle icon/component-info-circle)
(def icon-warning' icon/class-warning)
(def icon-warning icon/component-warning)
(def icon-warning-circle' icon/class-warning-circle)
(def icon-warning-circle icon/component-warning-circle)
(def icon-warning-sign' icon/class-warning-sign)
(def icon-warning-sign icon/component-warning-sign)

(def icon-child' icon/class-child)
(def icon-child icon/component-child)
(def icon-doctor' icon/class-doctor)
(def icon-doctor icon/component-doctor)
(def icon-handicap' icon/class-handicap)
(def icon-handicap icon/component-handicap)
(def icon-spy' icon/class-spy)
(def icon-spy icon/component-spy)
(def icon-student' icon/class-student)
(def icon-student icon/component-student)
(def icon-user' icon/class-user)
(def icon-user icon/component-user)
(def icon-users' icon/class-users)
(def icon-users icon/component-users)

(def icon-female' icon/class-female)
(def icon-female icon/component-female)
(def icon-gay' icon/class-gay)
(def icon-gay icon/component-gay)
(def icon-heterosexual' icon/class-heterosexual)
(def icon-heterosexual icon/component-heterosexual)
(def icon-intergender' icon/class-intergender)
(def icon-intergender icon/component-intergender)
(def icon-lesbian' icon/class-lesbian)
(def icon-lesbian icon/component-lesbian)
(def icon-male' icon/class-male)
(def icon-male icon/component-male)
(def icon-man' icon/class-man)
(def icon-man icon/component-man)
(def icon-neuter' icon/class-neuter)
(def icon-neuter icon/component-neuter)
(def icon-non-binary-transgender' icon/class-non-binary-transgender)
(def icon-non-binary-transgender icon/component-non-binary-transgender)
(def icon-transgender' icon/class-transgender)
(def icon-transgender icon/component-transgender)
(def icon-other-gender' icon/class-other-gender)
(def icon-other-gender icon/component-other-gender)
(def icon-other-gender-horizontal' icon/class-other-gender-horizontal)
(def icon-other-gender-horizontal icon/component-other-gender-horizontal)
(def icon-other-gender-vertical' icon/class-other-gender-vertical)
(def icon-other-gender-vertical icon/component-other-gender-vertical)
(def icon-woman' icon/class-woman)
(def icon-woman icon/component-woman)

(def icon-grid-layout' icon/class-grid-layout)
(def icon-grid-layout icon/component-grid-layout)
(def icon-list-layout' icon/class-list-layout)
(def icon-list-layout icon/component-list-layout)
(def icon-block-layout' icon/class-block-layout)
(def icon-block-layout icon/component-block-layout)
(def icon-zoom' icon/class-zoom)
(def icon-zoom icon/component-zoom)
(def icon-zoom-out' icon/class-zoom-out)
(def icon-zoom-out icon/component-zoom-out)
(def icon-resize-vertical' icon/class-resize-vertical)
(def icon-resize-vertical icon/component-resize-vertical)
(def icon-resize-horizontal' icon/class-resize-horizontal)
(def icon-resize-horizontal icon/component-resize-horizontal)
(def icon-maximize' icon/class-maximize)
(def icon-maximize icon/component-maximize)
(def icon-crop' icon/class-crop)
(def icon-crop icon/component-crop)

(def icon-anchor' icon/class-anchor)
(def icon-anchor icon/component-anchor)
(def icon-bar' icon/class-bar)
(def icon-bar icon/component-bar)
(def icon-bomb' icon/class-bomb)
(def icon-bomb icon/component-bomb)
(def icon-book' icon/class-book)
(def icon-book icon/component-book)
(def icon-bullseye' icon/class-bullseye)
(def icon-bullseye icon/component-bullseye)
(def icon-calculator' icon/class-calculator)
(def icon-calculator icon/component-calculator)
(def icon-checkered-flag' icon/class-checkered-flag)
(def icon-checkered-flag icon/component-checkered-flag)
(def icon-cocktail' icon/class-cocktail)
(def icon-cocktail icon/component-cocktail)
(def icon-diamond' icon/class-diamond)
(def icon-diamond icon/component-diamond)
(def icon-fax' icon/class-fax)
(def icon-fax icon/component-fax)
(def icon-fire-extinguisher' icon/class-fire-extinguisher)
(def icon-fire-extinguisher icon/component-fire-extinguisher)
(def icon-fire' icon/class-fire)
(def icon-fire icon/component-fire)
(def icon-gift' icon/class-gift)
(def icon-gift icon/component-gift)
(def icon-leaf' icon/class-leaf)
(def icon-leaf icon/component-leaf)
(def icon-legal' icon/class-legal)
(def icon-legal icon/component-legal)
(def icon-lemon' icon/class-lemon)
(def icon-lemon icon/component-lemon)
(def icon-life-ring' icon/class-life-ring)
(def icon-life-ring icon/component-life-ring)
(def icon-lightning' icon/class-lightning)
(def icon-lightning icon/component-lightning)
(def icon-magnet' icon/class-magnet)
(def icon-magnet icon/component-magnet)
(def icon-money' icon/class-money)
(def icon-money icon/component-money)
(def icon-moon' icon/class-moon)
(def icon-moon icon/component-moon)
(def icon-plane' icon/class-plane)
(def icon-plane icon/component-plane)
(def icon-puzzle' icon/class-puzzle)
(def icon-puzzle icon/component-puzzle)
(def icon-rain' icon/class-rain)
(def icon-rain icon/component-rain)
(def icon-road' icon/class-road)
(def icon-road icon/component-road)
(def icon-rocket' icon/class-rocket)
(def icon-rocket icon/component-rocket)
(def icon-shipping' icon/class-shipping)
(def icon-shipping icon/component-shipping)
(def icon-soccer' icon/class-soccer)
(def icon-soccer icon/component-soccer)
(def icon-suitcase' icon/class-suitcase)
(def icon-suitcase icon/component-suitcase)
(def icon-sun' icon/class-sun)
(def icon-sun icon/component-sun)
(def icon-travel' icon/class-travel)
(def icon-travel icon/component-travel)
(def icon-treatment' icon/class-treatment)
(def icon-treatment icon/component-treatment)
(def icon-world' icon/class-world)
(def icon-world icon/component-world)

(def icon-asterisk' icon/class-asterisk)
(def icon-asterisk icon/component-asterisk)
(def icon-certificate' icon/class-certificate)
(def icon-certificate icon/component-certificate)
(def icon-circle' icon/class-circle)
(def icon-circle icon/component-circle)
(def icon-circle-notched' icon/class-circle-notched)
(def icon-circle-notched icon/component-circle-notched)
(def icon-circle-thin' icon/class-circle-thin)
(def icon-circle-thin icon/component-circle-thin)
(def icon-crosshairs' icon/class-crosshairs)
(def icon-crosshairs icon/component-crosshairs)
(def icon-cube' icon/class-cube)
(def icon-cube icon/component-cube)
(def icon-cubes' icon/class-cubes)
(def icon-cubes icon/component-cubes)
(def icon-ellipsis-horizontal' icon/class-ellipsis-horizontal)
(def icon-ellipsis-horizontal icon/component-ellipsis-horizontal)
(def icon-ellipsis-vertical' icon/class-ellipsis-vertical)
(def icon-ellipsis-vertical icon/component-ellipsis-vertical)
(def icon-quote-left' icon/class-quote-left)
(def icon-quote-left icon/component-quote-left)
(def icon-quote-right' icon/class-quote-right)
(def icon-quote-right icon/component-quote-right)
(def icon-spinner' icon/class-spinner)
(def icon-spinner icon/component-spinner)
(def icon-square' icon/class-square)
(def icon-square icon/component-square)
(def icon-square-outline' icon/class-square-outline)
(def icon-square-outline icon/component-square-outline)

(def icon-add-circle' icon/class-add-circle)
(def icon-add-circle icon/component-add-circle)
(def icon-add-square' icon/class-add-square)
(def icon-add-square icon/component-add-square)
(def icon-check-circle' icon/class-check-circle)
(def icon-check-circle icon/component-check-circle)
(def icon-check-circle-outline' icon/class-check-circle-outline)
(def icon-check-circle-outline icon/component-check-circle-outline)
(def icon-check-square' icon/class-check-square)
(def icon-check-square icon/component-check-square)
(def icon-checkmark-box' icon/class-checkmark-box)
(def icon-checkmark-box icon/component-checkmark-box)
(def icon-checkmark' icon/class-checkmark)
(def icon-checkmark icon/component-checkmark)
(def icon-minus-circle' icon/class-minus-circle)
(def icon-minus-circle icon/component-minus-circle)
(def icon-minus' icon/class-minus)
(def icon-minus icon/component-minus)
(def icon-minus-square' icon/class-minus-square)
(def icon-minus-square icon/component-minus-square)
(def icon-minus-square-outline' icon/class-minus-square-outline)
(def icon-minus-square-outline icon/component-minus-square-outline)
(def icon-move' icon/class-move)
(def icon-move icon/component-move)
(def icon-plus' icon/class-plus)
(def icon-plus icon/component-plus)
(def icon-plus-square-outline' icon/class-plus-square-outline)
(def icon-plus-square-outline icon/component-plus-square-outline)
(def icon-radio' icon/class-radio)
(def icon-radio icon/component-radio)
(def icon-remove-circle' icon/class-remove-circle)
(def icon-remove-circle icon/component-remove-circle)
(def icon-remove-circle-outline' icon/class-remove-circle-outline)
(def icon-remove-circle-outline icon/component-remove-circle-outline)
(def icon-remove' icon/class-remove)
(def icon-remove icon/component-remove)
(def icon-selected-radio' icon/class-selected-radio)
(def icon-selected-radio icon/component-selected-radio)
(def icon-toggle-off' icon/class-toggle-off)
(def icon-toggle-off icon/component-toggle-off)
(def icon-toggle-on' icon/class-toggle-on)
(def icon-toggle-on icon/component-toggle-on)

(def icon-area-chart' icon/class-area-chart)
(def icon-area-chart icon/component-area-chart)
(def icon-bar-chart' icon/class-bar-chart)
(def icon-bar-chart icon/component-bar-chart)
(def icon-camera-retro' icon/class-camera-retro)
(def icon-camera-retro icon/component-camera-retro)
(def icon-newspaper' icon/class-newspaper)
(def icon-newspaper icon/component-newspaper)
(def icon-film' icon/class-film)
(def icon-film icon/component-film)
(def icon-line-chart' icon/class-line-chart)
(def icon-line-chart icon/component-line-chart)
(def icon-photo' icon/class-photo)
(def icon-photo icon/component-photo)
(def icon-pie-chart' icon/class-pie-chart)
(def icon-pie-chart icon/component-pie-chart)
(def icon-sound' icon/class-sound)
(def icon-sound icon/component-sound)

(def icon-angle-double-down' icon/class-angle-double-down)
(def icon-angle-double-down icon/component-angle-double-down)
(def icon-angle-double-left' icon/class-angle-double-left)
(def icon-angle-double-left icon/component-angle-double-left)
(def icon-angle-double-right' icon/class-angle-double-right)
(def icon-angle-double-right icon/component-angle-double-right)
(def icon-angle-double-up' icon/class-angle-double-up)
(def icon-angle-double-up icon/component-angle-double-up)
(def icon-angle-down' icon/class-angle-down)
(def icon-angle-down icon/component-angle-down)
(def icon-angle-left' icon/class-angle-left)
(def icon-angle-left icon/component-angle-left)
(def icon-angle-right' icon/class-angle-right)
(def icon-angle-right icon/component-angle-right)
(def icon-angle-up' icon/class-angle-up)
(def icon-angle-up icon/component-angle-up)
(def icon-arrow-circle-down' icon/class-arrow-circle-down)
(def icon-arrow-circle-down icon/component-arrow-circle-down)
(def icon-arrow-circle-left' icon/class-arrow-circle-left)
(def icon-arrow-circle-left icon/component-arrow-circle-left)
(def icon-arrow-circle-outline-down' icon/class-arrow-circle-outline-down)
(def icon-arrow-circle-outline-down icon/component-arrow-circle-outline-down)
(def icon-arrow-circle-outline-left' icon/class-arrow-circle-outline-left)
(def icon-arrow-circle-outline-left icon/component-arrow-circle-outline-left)
(def icon-arrow-circle-outline-right' icon/class-arrow-circle-outline-right)
(def icon-arrow-circle-outline-right icon/component-arrow-circle-outline-right)
(def icon-arrow-circle-outline-up' icon/class-arrow-circle-outline-up)
(def icon-arrow-circle-outline-up icon/component-arrow-circle-outline-up)
(def icon-arrow-circle-right' icon/class-arrow-circle-right)
(def icon-arrow-circle-right icon/component-arrow-circle-right)
(def icon-arrow-circle-up' icon/class-arrow-circle-up)
(def icon-arrow-circle-up icon/component-arrow-circle-up)
(def icon-arrow-down' icon/class-arrow-down)
(def icon-arrow-down icon/component-arrow-down)
(def icon-arrow-left' icon/class-arrow-left)
(def icon-arrow-left icon/component-arrow-left)
(def icon-arrow-right' icon/class-arrow-right)
(def icon-arrow-right icon/component-arrow-right)
(def icon-arrow-up' icon/class-arrow-up)
(def icon-arrow-up icon/component-arrow-up)
(def icon-caret-down' icon/class-caret-down)
(def icon-caret-down icon/component-caret-down)
(def icon-caret-left' icon/class-caret-left)
(def icon-caret-left icon/component-caret-left)
(def icon-caret-right' icon/class-caret-right)
(def icon-caret-right icon/component-caret-right)
(def icon-caret-up' icon/class-caret-up)
(def icon-caret-up icon/component-caret-up)
(def icon-chevron-circle-down' icon/class-chevron-circle-down)
(def icon-chevron-circle-down icon/component-chevron-circle-down)
(def icon-chevron-circle-left' icon/class-chevron-circle-left)
(def icon-chevron-circle-left icon/component-chevron-circle-left)
(def icon-chevron-circle-right' icon/class-chevron-circle-right)
(def icon-chevron-circle-right icon/component-chevron-circle-right)
(def icon-chevron-circle-up' icon/class-chevron-circle-up)
(def icon-chevron-circle-up icon/component-chevron-circle-up)
(def icon-chevron-down' icon/class-chevron-down)
(def icon-chevron-down icon/component-chevron-down)
(def icon-chevron-left' icon/class-chevron-left)
(def icon-chevron-left icon/component-chevron-left)
(def icon-chevron-right' icon/class-chevron-right)
(def icon-chevron-right icon/component-chevron-right)
(def icon-chevron-up' icon/class-chevron-up)
(def icon-chevron-up icon/component-chevron-up)
(def icon-long-arrow-down' icon/class-long-arrow-down)
(def icon-long-arrow-down icon/component-long-arrow-down)
(def icon-long-arrow-left' icon/class-long-arrow-left)
(def icon-long-arrow-left icon/component-long-arrow-left)
(def icon-long-arrow-right' icon/class-long-arrow-right)
(def icon-long-arrow-right icon/component-long-arrow-right)
(def icon-long-arrow-up' icon/class-long-arrow-up)
(def icon-long-arrow-up icon/component-long-arrow-up)
(def icon-pointing-down' icon/class-pointing-down)
(def icon-pointing-down icon/component-pointing-down)
(def icon-pointing-left' icon/class-pointing-left)
(def icon-pointing-left icon/component-pointing-left)
(def icon-pointing-right' icon/class-pointing-right)
(def icon-pointing-right icon/component-pointing-right)
(def icon-pointing-up' icon/class-pointing-up)
(def icon-pointing-up icon/component-pointing-up)
(def icon-toggle-down' icon/class-toggle-down)
(def icon-toggle-down icon/component-toggle-down)
(def icon-toggle-left' icon/class-toggle-left)
(def icon-toggle-left icon/component-toggle-left)
(def icon-toggle-right' icon/class-toggle-right)
(def icon-toggle-right icon/component-toggle-right)
(def icon-toggle-up' icon/class-toggle-up)
(def icon-toggle-up icon/component-toggle-up)

(def icon-desktop' icon/class-desktop)
(def icon-desktop icon/component-desktop)
(def icon-disk-outline' icon/class-disk-outline)
(def icon-disk-outline icon/component-disk-outline)
(def icon-file-archive-outline' icon/class-file-archive-outline)
(def icon-file-archive-outline icon/component-file-archive-outline)
(def icon-file-audio-outline' icon/class-file-audio-outline)
(def icon-file-audio-outline icon/component-file-audio-outline)
(def icon-file-code-outline' icon/class-file-code-outline)
(def icon-file-code-outline icon/component-file-code-outline)
(def icon-file-excel-outline' icon/class-file-excel-outline)
(def icon-file-excel-outline icon/component-file-excel-outline)
(def icon-file' icon/class-file)
(def icon-file icon/component-file)
(def icon-file-image-outline' icon/class-file-image-outline)
(def icon-file-image-outline icon/component-file-image-outline)
(def icon-file-outline' icon/class-file-outline)
(def icon-file-outline icon/component-file-outline)
(def icon-file-pdf-outline' icon/class-file-pdf-outline)
(def icon-file-pdf-outline icon/component-file-pdf-outline)
(def icon-file-powerpoint-outline' icon/class-file-powerpoint-outline)
(def icon-file-powerpoint-outline icon/component-file-powerpoint-outline)
(def icon-file-text' icon/class-file-text)
(def icon-file-text icon/component-file-text)
(def icon-file-text-outline' icon/class-file-text-outline)
(def icon-file-text-outline icon/component-file-text-outline)
(def icon-file-video-outline' icon/class-file-video-outline)
(def icon-file-video-outline icon/component-file-video-outline)
(def icon-file-word-outline' icon/class-file-word-outline)
(def icon-file-word-outline icon/component-file-word-outline)
(def icon-folder' icon/class-folder)
(def icon-folder icon/component-folder)
(def icon-folder-open' icon/class-folder-open)
(def icon-folder-open icon/component-folder-open)
(def icon-folder-open-outline' icon/class-folder-open-outline)
(def icon-folder-open-outline icon/component-folder-open-outline)
(def icon-folder-outline' icon/class-folder-outline)
(def icon-folder-outline icon/component-folder-outline)
(def icon-game' icon/class-game)
(def icon-game icon/component-game)
(def icon-keyboard' icon/class-keyboard)
(def icon-keyboard icon/component-keyboard)
(def icon-laptop' icon/class-laptop)
(def icon-laptop icon/component-laptop)
(def icon-level-down' icon/class-level-down)
(def icon-level-down icon/component-level-down)
(def icon-level-up' icon/class-level-up)
(def icon-level-up icon/component-level-up)
(def icon-mobile' icon/class-mobile)
(def icon-mobile icon/component-mobile)
(def icon-power' icon/class-power)
(def icon-power icon/component-power)
(def icon-plug' icon/class-plug)
(def icon-plug icon/component-plug)
(def icon-tablet' icon/class-tablet)
(def icon-tablet icon/component-tablet)
(def icon-trash' icon/class-trash)
(def icon-trash icon/component-trash)
(def icon-trash-outline' icon/class-trash-outline)
(def icon-trash-outline icon/component-trash-outline)

(def icon-barcode' icon/class-barcode)
(def icon-barcode icon/component-barcode)
(def icon-css3' icon/class-css3)
(def icon-css3 icon/component-css3)
(def icon-database' icon/class-database)
(def icon-database icon/component-database)
(def icon-fork' icon/class-fork)
(def icon-fork icon/component-fork)
(def icon-html5' icon/class-html5)
(def icon-html5 icon/component-html5)
(def icon-openid' icon/class-openid)
(def icon-openid icon/component-openid)
(def icon-qrcode' icon/class-qrcode)
(def icon-qrcode icon/component-qrcode)
(def icon-rss' icon/class-rss)
(def icon-rss icon/component-rss)
(def icon-rss-square' icon/class-rss-square)
(def icon-rss-square icon/component-rss-square)
(def icon-server' icon/class-server)
(def icon-server icon/component-server)

(def icon-empty-heart' icon/class-empty-heart)
(def icon-empty-heart icon/component-empty-heart)
(def icon-empty-star' icon/class-empty-star)
(def icon-empty-star icon/component-empty-star)
(def icon-frown' icon/class-frown)
(def icon-frown icon/component-frown)
(def icon-heart' icon/class-heart)
(def icon-heart icon/component-heart)
(def icon-meh' icon/class-meh)
(def icon-meh icon/component-meh)
(def icon-smile' icon/class-smile)
(def icon-smile icon/component-smile)
(def icon-star-half-empty' icon/class-star-half-empty)
(def icon-star-half-empty icon/component-star-half-empty)
(def icon-star-half' icon/class-star-half)
(def icon-star-half icon/component-star-half)
(def icon-star' icon/class-star)
(def icon-star icon/component-star)
(def icon-thumbs-down' icon/class-thumbs-down)
(def icon-thumbs-down icon/component-thumbs-down)
(def icon-thumbs-outline-down' icon/class-thumbs-outline-down)
(def icon-thumbs-outline-down icon/component-thumbs-outline-down)
(def icon-thumbs-outline-up' icon/class-thumbs-outline-up)
(def icon-thumbs-outline-up icon/component-thumbs-outline-up)
(def icon-thumbs-up' icon/class-thumbs-up)
(def icon-thumbs-up icon/component-thumbs-up)

(def icon-backward' icon/class-backward)
(def icon-backward icon/component-backward)
(def icon-eject' icon/class-eject)
(def icon-eject icon/component-eject)
(def icon-fast-backward' icon/class-fast-backward)
(def icon-fast-backward icon/component-fast-backward)
(def icon-fast-forward' icon/class-fast-forward)
(def icon-fast-forward icon/component-fast-forward)
(def icon-forward' icon/class-forward)
(def icon-forward icon/component-forward)
(def icon-music' icon/class-music)
(def icon-music icon/component-music)
(def icon-mute' icon/class-mute)
(def icon-mute icon/component-mute)
(def icon-pause' icon/class-pause)
(def icon-pause icon/component-pause)
(def icon-play' icon/class-play)
(def icon-play icon/component-play)
(def icon-record' icon/class-record)
(def icon-record icon/component-record)
(def icon-step-backward' icon/class-step-backward)
(def icon-step-backward icon/component-step-backward)
(def icon-step-forward' icon/class-step-forward)
(def icon-step-forward icon/component-step-forward)
(def icon-stop' icon/class-stop)
(def icon-stop icon/component-stop)
(def icon-unmute' icon/class-unmute)
(def icon-unmute icon/component-unmute)
(def icon-video-play' icon/class-video-play)
(def icon-video-play icon/component-video-play)
(def icon-video-play-outline' icon/class-video-play-outline)
(def icon-video-play-outline icon/component-video-play-outline)
(def icon-volume-down' icon/class-volume-down)
(def icon-volume-down icon/component-volume-down)
(def icon-volume-off' icon/class-volume-off)
(def icon-volume-off icon/component-volume-off)
(def icon-volume-up' icon/class-volume-up)
(def icon-volume-up icon/component-volume-up)

(def icon-building' icon/class-building)
(def icon-building icon/component-building)
(def icon-building-outline' icon/class-building-outline)
(def icon-building-outline icon/component-building-outline)
(def icon-car' icon/class-car)
(def icon-car icon/component-car)
(def icon-coffee' icon/class-coffee)
(def icon-coffee icon/component-coffee)
(def icon-emergency' icon/class-emergency)
(def icon-emergency icon/component-emergency)
(def icon-first-aid' icon/class-first-aid)
(def icon-first-aid icon/component-first-aid)
(def icon-food' icon/class-food)
(def icon-food icon/component-food)
(def icon-h' icon/class-h)
(def icon-h icon/component-h)
(def icon-hospital' icon/class-hospital)
(def icon-hospital icon/component-hospital)
(def icon-location-arrow' icon/class-location-arrow)
(def icon-location-arrow icon/component-location-arrow)
(def icon-marker' icon/class-marker)
(def icon-marker icon/component-marker)
(def icon-military' icon/class-military)
(def icon-military icon/component-military)
(def icon-paw' icon/class-paw)
(def icon-paw icon/component-paw)
(def icon-space-shuttle' icon/class-space-shuttle)
(def icon-space-shuttle icon/component-space-shuttle)
(def icon-spoon' icon/class-spoon)
(def icon-spoon icon/component-spoon)
(def icon-taxi' icon/class-taxi)
(def icon-taxi icon/component-taxi)
(def icon-tree' icon/class-tree)
(def icon-tree icon/component-tree)
(def icon-university' icon/class-university)
(def icon-university icon/component-university)

(def icon-columns' icon/class-columns)
(def icon-columns icon/component-columns)
(def icon-sort-alphabet-ascending' icon/class-sort-alphabet-ascending)
(def icon-sort-alphabet-ascending icon/component-sort-alphabet-ascending)
(def icon-sort-alphabet-descending' icon/class-sort-alphabet-descending)
(def icon-sort-alphabet-descending icon/component-sort-alphabet-descending)
(def icon-sort-ascending' icon/class-sort-ascending)
(def icon-sort-ascending icon/component-sort-ascending)
(def icon-sort-content-ascending' icon/class-sort-content-ascending)
(def icon-sort-content-ascending icon/component-sort-content-ascending)
(def icon-sort-content-descending' icon/class-sort-content-descending)
(def icon-sort-content-descending icon/component-sort-content-descending)
(def icon-sort-descending' icon/class-sort-descending)
(def icon-sort-descending icon/component-sort-descending)
(def icon-sort' icon/class-sort)
(def icon-sort icon/component-sort)
(def icon-sort-numeric-ascending' icon/class-sort-numeric-ascending)
(def icon-sort-numeric-ascending icon/component-sort-numeric-ascending)
(def icon-sort-numeric-descending' icon/class-sort-numeric-descending)
(def icon-sort-numeric-descending icon/component-sort-numeric-descending)
(def icon-table' icon/class-table)
(def icon-table icon/component-table)

(def icon-align-center' icon/class-align-center)
(def icon-align-center icon/component-align-center)
(def icon-align-justify' icon/class-align-justify)
(def icon-align-justify icon/component-align-justify)
(def icon-align-left' icon/class-align-left)
(def icon-align-left icon/component-align-left)
(def icon-align-right' icon/class-align-right)
(def icon-align-right icon/component-align-right)
(def icon-attach' icon/class-attach)
(def icon-attach icon/component-attach)
(def icon-bold' icon/class-bold)
(def icon-bold icon/component-bold)
(def icon-copy' icon/class-copy)
(def icon-copy icon/component-copy)
(def icon-cut' icon/class-cut)
(def icon-cut icon/component-cut)
(def icon-font' icon/class-font)
(def icon-font icon/component-font)
(def icon-header' icon/class-header)
(def icon-header icon/component-header)
(def icon-indent' icon/class-indent)
(def icon-indent icon/component-indent)
(def icon-italic' icon/class-italic)
(def icon-italic icon/component-italic)
(def icon-linkify' icon/class-linkify)
(def icon-linkify icon/component-linkify)
(def icon-list' icon/class-list)
(def icon-list icon/component-list)
(def icon-ordered-list' icon/class-ordered-list)
(def icon-ordered-list icon/component-ordered-list)
(def icon-outdent' icon/class-outdent)
(def icon-outdent icon/component-outdent)
(def icon-paragraph' icon/class-paragraph)
(def icon-paragraph icon/component-paragraph)
(def icon-paste' icon/class-paste)
(def icon-paste icon/component-paste)
(def icon-save' icon/class-save)
(def icon-save icon/component-save)
(def icon-strikethrough' icon/class-strikethrough)
(def icon-strikethrough icon/component-strikethrough)
(def icon-subscript' icon/class-subscript)
(def icon-subscript icon/component-subscript)
(def icon-superscript' icon/class-superscript)
(def icon-superscript icon/component-superscript)
(def icon-text-height' icon/class-text-height)
(def icon-text-height icon/component-text-height)
(def icon-text-width' icon/class-text-width)
(def icon-text-width icon/component-text-width)
(def icon-underline' icon/class-underline)
(def icon-underline icon/component-underline)
(def icon-unlink' icon/class-unlink)
(def icon-unlink icon/component-unlink)
(def icon-unordered-list' icon/class-unordered-list)
(def icon-unordered-list icon/component-unordered-list)

(def icon-dollar' icon/class-dollar)
(def icon-dollar icon/component-dollar)
(def icon-euro' icon/class-euro)
(def icon-euro icon/component-euro)
(def icon-lira' icon/class-lira)
(def icon-lira icon/component-lira)
(def icon-pound' icon/class-pound)
(def icon-pound icon/component-pound)
(def icon-ruble' icon/class-ruble)
(def icon-ruble icon/component-ruble)
(def icon-rupee' icon/class-rupee)
(def icon-rupee icon/component-rupee)
(def icon-won' icon/class-won)
(def icon-won icon/component-won)
(def icon-shekel' icon/class-shekel)
(def icon-shekel icon/component-shekel)
(def icon-yen' icon/class-yen)
(def icon-yen icon/component-yen)

(def icon-american-express' icon/class-american-express)
(def icon-american-express icon/component-american-express)
(def icon-discover' icon/class-discover)
(def icon-discover icon/component-discover)
(def icon-google-wallet' icon/class-google-wallet)
(def icon-google-wallet icon/component-google-wallet)
(def icon-mastercard' icon/class-mastercard)
(def icon-mastercard icon/component-mastercard)
(def icon-paypal-card' icon/class-paypal-card)
(def icon-paypal-card icon/component-paypal-card)
(def icon-paypal' icon/class-paypal)
(def icon-paypal icon/component-paypal)
(def icon-stripe' icon/class-stripe)
(def icon-stripe icon/component-stripe)
(def icon-visa' icon/class-visa)
(def icon-visa icon/component-visa)

(def icon-adn' icon/class-adn)
(def icon-adn icon/component-adn)
(def icon-android' icon/class-android)
(def icon-android icon/component-android)
(def icon-angellist' icon/class-angellist)
(def icon-angellist icon/component-angellist)
(def icon-apple' icon/class-apple)
(def icon-apple icon/component-apple)
(def icon-behance' icon/class-behance)
(def icon-behance icon/component-behance)
(def icon-behance-square' icon/class-behance-square)
(def icon-behance-square icon/component-behance-square)
(def icon-bitbucket' icon/class-bitbucket)
(def icon-bitbucket icon/component-bitbucket)
(def icon-bitbucket-square' icon/class-bitbucket-square)
(def icon-bitbucket-square icon/component-bitbucket-square)
(def icon-bitcoin' icon/class-bitcoin)
(def icon-bitcoin icon/component-bitcoin)
(def icon-buysellads' icon/class-buysellads)
(def icon-buysellads icon/component-buysellads)
(def icon-codepen' icon/class-codepen)
(def icon-codepen icon/component-codepen)
(def icon-connectdevelop' icon/class-connectdevelop)
(def icon-connectdevelop icon/component-connectdevelop)
(def icon-dashcube' icon/class-dashcube)
(def icon-dashcube icon/component-dashcube)
(def icon-delicious' icon/class-delicious)
(def icon-delicious icon/component-delicious)
(def icon-deviantart' icon/class-deviantart)
(def icon-deviantart icon/component-deviantart)
(def icon-digg' icon/class-digg)
(def icon-digg icon/component-digg)
(def icon-dribbble' icon/class-dribbble)
(def icon-dribbble icon/component-dribbble)
(def icon-dropbox' icon/class-dropbox)
(def icon-dropbox icon/component-dropbox)
(def icon-drupal' icon/class-drupal)
(def icon-drupal icon/component-drupal)
(def icon-empire' icon/class-empire)
(def icon-empire icon/component-empire)
(def icon-facebook' icon/class-facebook)
(def icon-facebook icon/component-facebook)
(def icon-facebook-square' icon/class-facebook-square)
(def icon-facebook-square icon/component-facebook-square)
(def icon-flickr' icon/class-flickr)
(def icon-flickr icon/component-flickr)
(def icon-forumbee' icon/class-forumbee)
(def icon-forumbee icon/component-forumbee)
(def icon-foursquare' icon/class-foursquare)
(def icon-foursquare icon/component-foursquare)
(def icon-git' icon/class-git)
(def icon-git icon/component-git)
(def icon-git-square' icon/class-git-square)
(def icon-git-square icon/component-git-square)
(def icon-github-alternate' icon/class-github-alternate)
(def icon-github-alternate icon/component-github-alternate)
(def icon-github' icon/class-github)
(def icon-github icon/component-github)
(def icon-github-square' icon/class-github-square)
(def icon-github-square icon/component-github-square)
(def icon-gittip' icon/class-gittip)
(def icon-gittip icon/component-gittip)
(def icon-google' icon/class-google)
(def icon-google icon/component-google)
(def icon-google-plus' icon/class-google-plus)
(def icon-google-plus icon/component-google-plus)
(def icon-google-plus-square' icon/class-google-plus-square)
(def icon-google-plus-square icon/component-google-plus-square)
(def icon-hacker-news' icon/class-hacker-news)
(def icon-hacker-news icon/component-hacker-news)
(def icon-instagram' icon/class-instagram)
(def icon-instagram icon/component-instagram)
(def icon-ioxhost' icon/class-ioxhost)
(def icon-ioxhost icon/component-ioxhost)
(def icon-joomla' icon/class-joomla)
(def icon-joomla icon/component-joomla)
(def icon-jsfiddle' icon/class-jsfiddle)
(def icon-jsfiddle icon/component-jsfiddle)
(def icon-lastfm' icon/class-lastfm)
(def icon-lastfm icon/component-lastfm)
(def icon-lastfm-square' icon/class-lastfm-square)
(def icon-lastfm-square icon/component-lastfm-square)
(def icon-leanpub' icon/class-leanpub)
(def icon-leanpub icon/component-leanpub)
(def icon-linkedin' icon/class-linkedin)
(def icon-linkedin icon/component-linkedin)
(def icon-linkedin-square' icon/class-linkedin-square)
(def icon-linkedin-square icon/component-linkedin-square)
(def icon-linux' icon/class-linux)
(def icon-linux icon/component-linux)
(def icon-maxcdn' icon/class-maxcdn)
(def icon-maxcdn icon/component-maxcdn)
(def icon-meanpath' icon/class-meanpath)
(def icon-meanpath icon/component-meanpath)
(def icon-medium' icon/class-medium)
(def icon-medium icon/component-medium)
(def icon-pagelines' icon/class-pagelines)
(def icon-pagelines icon/component-pagelines)
(def icon-pied-piper-alternate' icon/class-pied-piper-alternate)
(def icon-pied-piper-alternate icon/component-pied-piper-alternate)
(def icon-pied-piper' icon/class-pied-piper)
(def icon-pied-piper icon/component-pied-piper)
(def icon-pinterest' icon/class-pinterest)
(def icon-pinterest icon/component-pinterest)
(def icon-pinterest-square' icon/class-pinterest-square)
(def icon-pinterest-square icon/component-pinterest-square)
(def icon-qq' icon/class-qq)
(def icon-qq icon/component-qq)
(def icon-rebel' icon/class-rebel)
(def icon-rebel icon/component-rebel)
(def icon-reddit' icon/class-reddit)
(def icon-reddit icon/component-reddit)
(def icon-reddit-square' icon/class-reddit-square)
(def icon-reddit-square icon/component-reddit-square)
(def icon-renren' icon/class-renren)
(def icon-renren icon/component-renren)
(def icon-sellsy' icon/class-sellsy)
(def icon-sellsy icon/component-sellsy)
(def icon-shirtsinbulk' icon/class-shirtsinbulk)
(def icon-shirtsinbulk icon/component-shirtsinbulk)
(def icon-simplybuilt' icon/class-simplybuilt)
(def icon-simplybuilt icon/component-simplybuilt)
(def icon-skyatlas' icon/class-skyatlas)
(def icon-skyatlas icon/component-skyatlas)
(def icon-skype' icon/class-skype)
(def icon-skype icon/component-skype)
(def icon-slack' icon/class-slack)
(def icon-slack icon/component-slack)
(def icon-slideshare' icon/class-slideshare)
(def icon-slideshare icon/component-slideshare)
(def icon-soundcloud' icon/class-soundcloud)
(def icon-soundcloud icon/component-soundcloud)
(def icon-spotify' icon/class-spotify)
(def icon-spotify icon/component-spotify)
(def icon-stack-exchange' icon/class-stack-exchange)
(def icon-stack-exchange icon/component-stack-exchange)
(def icon-stack-overflow' icon/class-stack-overflow)
(def icon-stack-overflow icon/component-stack-overflow)
(def icon-steam' icon/class-steam)
(def icon-steam icon/component-steam)
(def icon-steam-square' icon/class-steam-square)
(def icon-steam-square icon/component-steam-square)
(def icon-stumbleupon-circle' icon/class-stumbleupon-circle)
(def icon-stumbleupon-circle icon/component-stumbleupon-circle)
(def icon-stumbleupon' icon/class-stumbleupon)
(def icon-stumbleupon icon/component-stumbleupon)
(def icon-tencent-weibo' icon/class-tencent-weibo)
(def icon-tencent-weibo icon/component-tencent-weibo)
(def icon-trello' icon/class-trello)
(def icon-trello icon/component-trello)
(def icon-tumblr' icon/class-tumblr)
(def icon-tumblr icon/component-tumblr)
(def icon-tumblr-square' icon/class-tumblr-square)
(def icon-tumblr-square icon/component-tumblr-square)
(def icon-twitch' icon/class-twitch)
(def icon-twitch icon/component-twitch)
(def icon-twitter' icon/class-twitter)
(def icon-twitter icon/component-twitter)
(def icon-twitter-square' icon/class-twitter-square)
(def icon-twitter-square icon/component-twitter-square)
(def icon-viacoin' icon/class-viacoin)
(def icon-viacoin icon/component-viacoin)
(def icon-vimeo' icon/class-vimeo)
(def icon-vimeo icon/component-vimeo)
(def icon-vine' icon/class-vine)
(def icon-vine icon/component-vine)
(def icon-vk' icon/class-vk)
(def icon-vk icon/component-vk)
(def icon-wechat' icon/class-wechat)
(def icon-wechat icon/component-wechat)
(def icon-weibo' icon/class-weibo)
(def icon-weibo icon/component-weibo)
(def icon-whatsapp' icon/class-whatsapp)
(def icon-whatsapp icon/component-whatsapp)
(def icon-windows' icon/class-windows)
(def icon-windows icon/component-windows)
(def icon-wordpress' icon/class-wordpress)
(def icon-wordpress icon/component-wordpress)
(def icon-xing' icon/class-xing)
(def icon-xing icon/component-xing)
(def icon-xing-square' icon/class-xing-square)
(def icon-xing-square icon/component-xing-square)
(def icon-yahoo' icon/class-yahoo)
(def icon-yahoo icon/component-yahoo)
(def icon-yelp' icon/class-yelp)
(def icon-yelp icon/component-yelp)
(def icon-youtube' icon/class-youtube)
(def icon-youtube icon/component-youtube)
(def icon-youtube-play' icon/class-youtube-play)
(def icon-youtube-play icon/component-youtube-play)
(def icon-youtube-square' icon/class-youtube-square)
(def icon-youtube-square icon/component-youtube-square)
