(ns soda-ash.elements.flag-card
  (:require-macros
   [devcards.core :refer [defcard-doc
                          defcard-rg
                          mkdn-pprint-source]])
  (:require
   [reagent.core :as reagent]
   [soda-ash.core :as sa]
   [soda-ash.elements.flag :as flag]
   [clojure.string :as string]))


(defn list-keys [group-name]
  (->> flag/groups
       (filter #(= group-name
                   (:group-name %)))
       first
       :group-set
       (string/join ", ")))


(defcard-doc
  "# SUMMARY

  ## Types"
  (list-keys "types")
  )



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Types

(defn type-ae []
  [sa/flag-ae])

(defcard-doc
  (mkdn-pprint-source type-ae))

(defcard-rg
  [:div
   [type-ae]
   [sa/flag-af]
   [sa/flag-ag]
   [sa/flag-ai]
   [sa/flag-al]
   [sa/flag-am]
   [sa/flag-an]
   [sa/flag-ao]
   [sa/flag-ar]
   [sa/flag-as]
   [sa/flag-at]
   [sa/flag-au]
   [sa/flag-aw]
   [sa/flag-ax]
   [sa/flag-az]
   [sa/flag-ba]
   [sa/flag-bb]
   [sa/flag-bd]
   [sa/flag-be]
   [sa/flag-bf]
   [sa/flag-bg]
   [sa/flag-bh]
   [sa/flag-bi]
   [sa/flag-bj]
   [sa/flag-bm]
   [sa/flag-bn]
   [sa/flag-bo]
   [sa/flag-br]
   [sa/flag-bs]
   [sa/flag-bt]
   [sa/flag-bv]
   [sa/flag-bw]
   [sa/flag-by]
   [sa/flag-bz]
   [sa/flag-ca]
   [sa/flag-cc]
   [sa/flag-cd]
   [sa/flag-cf]
   [sa/flag-cg]
   [sa/flag-ch]
   [sa/flag-ci]
   [sa/flag-ck]
   [sa/flag-cl]
   [sa/flag-cm]
   [sa/flag-cn]
   [sa/flag-co]
   [sa/flag-cr]
   [sa/flag-cs]
   [sa/flag-cu]
   [sa/flag-cv]
   [sa/flag-cx]
   [sa/flag-cy]
   [sa/flag-cz]
   [sa/flag-de]
   [sa/flag-dj]
   [sa/flag-dk]
   [sa/flag-dm]
   [sa/flag-do]
   [sa/flag-dz]
   [sa/flag-ec]
   [sa/flag-ee]
   [sa/flag-eg]
   [sa/flag-eh]
   [sa/flag-er]
   [sa/flag-es]
   [sa/flag-et]
   [sa/flag-eu]
   [sa/flag-fi]
   [sa/flag-fj]
   [sa/flag-fk]
   [sa/flag-fm]
   [sa/flag-fo]
   [sa/flag-fr]
   [sa/flag-ga]
   [sa/flag-gb]
   [sa/flag-gd]
   [sa/flag-ge]
   [sa/flag-gf]
   [sa/flag-gh]
   [sa/flag-gi]
   [sa/flag-gl]
   [sa/flag-gm]
   [sa/flag-gn]
   [sa/flag-gp]
   [sa/flag-gq]
   [sa/flag-gr]
   [sa/flag-gs]
   [sa/flag-gt]
   [sa/flag-gu]
   [sa/flag-gw]
   [sa/flag-gy]
   [sa/flag-hk]
   [sa/flag-hm]
   [sa/flag-hn]
   [sa/flag-hr]
   [sa/flag-ht]
   [sa/flag-hu]
   [sa/flag-id]
   [sa/flag-ie]
   [sa/flag-il]
   [sa/flag-in]
   [sa/flag-io]
   [sa/flag-iq]
   [sa/flag-ir]
   [sa/flag-is]
   [sa/flag-it]
   [sa/flag-jm]
   [sa/flag-jo]
   [sa/flag-jp]
   [sa/flag-ke]
   [sa/flag-kg]
   [sa/flag-kh]
   [sa/flag-ki]
   [sa/flag-km]
   [sa/flag-kn]
   [sa/flag-kp]
   [sa/flag-kr]
   [sa/flag-kw]
   [sa/flag-ky]
   [sa/flag-kz]
   [sa/flag-la]
   [sa/flag-lb]
   [sa/flag-lc]
   [sa/flag-li]
   [sa/flag-lk]
   [sa/flag-lr]
   [sa/flag-ls]
   [sa/flag-lt]
   [sa/flag-lu]
   [sa/flag-lv]
   [sa/flag-ly]
   [sa/flag-ma]
   [sa/flag-mc]
   [sa/flag-md]
   [sa/flag-me]
   [sa/flag-mg]
   [sa/flag-mh]
   [sa/flag-mk]
   [sa/flag-ml]
   [sa/flag-mm]
   [sa/flag-mn]
   [sa/flag-mo]
   [sa/flag-mp]
   [sa/flag-mq]
   [sa/flag-mr]
   [sa/flag-ms]
   [sa/flag-mt]
   [sa/flag-mu]
   [sa/flag-mv]
   [sa/flag-mw]
   [sa/flag-mx]
   [sa/flag-my]
   [sa/flag-mz]
   [sa/flag-na]
   [sa/flag-nc]
   [sa/flag-ne]
   [sa/flag-nf]
   [sa/flag-ng]
   [sa/flag-ni]
   [sa/flag-nl]
   [sa/flag-no]
   [sa/flag-np]
   [sa/flag-nr]
   [sa/flag-nu]
   [sa/flag-nz]
   [sa/flag-om]
   [sa/flag-pa]
   [sa/flag-pe]
   [sa/flag-pf]
   [sa/flag-pg]
   [sa/flag-ph]
   [sa/flag-pk]
   [sa/flag-pl]
   [sa/flag-pm]
   [sa/flag-pn]
   [sa/flag-pr]
   [sa/flag-ps]
   [sa/flag-pt]
   [sa/flag-pw]
   [sa/flag-py]
   [sa/flag-qa]
   [sa/flag-re]
   [sa/flag-ro]
   [sa/flag-rs]
   [sa/flag-ru]
   [sa/flag-rw]
   [sa/flag-sa]
   [sa/flag-sb]
   [sa/flag-sc]
   [sa/flag-sd]
   [sa/flag-se]
   [sa/flag-sg]
   [sa/flag-sh]
   [sa/flag-si]
   [sa/flag-sj]
   [sa/flag-sk]
   [sa/flag-sl]
   [sa/flag-sm]
   [sa/flag-sn]
   [sa/flag-so]
   [sa/flag-sr]
   [sa/flag-st]
   [sa/flag-sv]
   [sa/flag-sy]
   [sa/flag-sz]
   [sa/flag-tc]
   [sa/flag-td]
   [sa/flag-tf]
   [sa/flag-tg]
   [sa/flag-th]
   [sa/flag-tj]
   [sa/flag-tk]
   [sa/flag-tl]
   [sa/flag-tm]
   [sa/flag-tn]
   [sa/flag-to]
   [sa/flag-tr]
   [sa/flag-tt]
   [sa/flag-tv]
   [sa/flag-tw]
   [sa/flag-tz]
   [sa/flag-ua]
   [sa/flag-ug]
   [sa/flag-um]
   [sa/flag-us]
   [sa/flag-uy]
   [sa/flag-uz]
   [sa/flag-va]
   [sa/flag-vc]
   [sa/flag-ve]
   [sa/flag-vg]
   [sa/flag-vi]
   [sa/flag-vn]
   [sa/flag-vu]
   [sa/flag-wf]
   [sa/flag-ws]
   [sa/flag-ye]
   [sa/flag-yt]
   [sa/flag-za]
   [sa/flag-zm]
   ])
